### ISSUE TITLE
[Web]-[Account] Birth date doesn't get saved 

### ISSUE THREAD

**Issue by Koriagami** [electro4orty/electro4ort-web#1]
If user selects any date in the datepicker and then saves the changes - the date is not getting saved:
- If account is opened again - the corresponding field appears to be empty
- Refreshing the page doesn't aid in this case

<details>
<summary>Video Example</summary>

[scrnli_zmW38imn9VzNL1.webm](https://github.com/user-attachments/assets/74f46d0a-451c-45c7-882d-1ff663f063f7)

</details>

**Comment by olehhapuk** [comment]
Fixed
